name: Raw API

on:
    push:
        branches: [main]
        paths:
            - "domains/*"
            - ".github/workflows/raw-api.yml"
            - "util/raw-api.js"
            - "util/reserved.json"

    workflow_dispatch:

concurrency:
    group: ${{ github.ref }}-raw-api
    cancel-in-progress: true

jobs:
    update:
        name: Update
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4

            - uses: actions/setup-node@v4
              with:
                  node-version: 20.x

            - run: |
                ls
                echo ---
                ls ../
                echo ---
                ls ../../

            - name: Update Data
              run: node util/raw-api.js

            - name: Commit
              uses: cpina/github-action-push-to-another-repository@main
              with:
                  source-directory: "raw-api"
                  destination-github-username: is-a-dev
                  destination-repository-name: raw-api
                  user-email: "bot@is-a.dev"
                  user-name: "is-a-dev-bot"
              env:
                  API_TOKEN_GITHUB: ${{ secrets.BOT }}
